In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv("/content/combined_data.csv")

In [ ]:
df.head()

label                                               text
0      1  ounce feather bowl hummingbird opec moment ala...
1      1  wulvob get your medircations online qnb ikud v...
2      0   computer connection from cnn com wednesday es...
3      1  university degree obtain a prosperous future m...
4      0  thanks for all your answers guys i know i shou...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7485 entries, 0 to 7484
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   label   7485 non-null   int64 
 1   text    7485 non-null   object
dtypes: int64(1), object(1)
memory usage: 117.1+ KB


In [ ]:
df['label'].value_counts(normalize= True)*100

label
1    53.253173
0    46.746827
Name: proportion, dtype: float64

In [ ]:
df['text'] = df['text'].apply(lambda x: x.lower())
df['text']

0       ounce feather bowl hummingbird opec moment ala...
1       wulvob get your medircations online qnb ikud v...
2        computer connection from cnn com wednesday es...
3       university degree obtain a prosperous future m...
4       thanks for all your answers guys i know i shou...
                              ...                        
7480    free video professor trial and digital camera ...
7481    ultimately the true stuff escapenumber no more...
7482    i will fix this .\nmark pickering\nchief techn...
7483    bill - i believe this was meant for you .\n- -...
7484    advertising is the principal reason why the bu...
Name: text, Length: 7485, dtype: object

In [ ]:
import string

def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))


In [ ]:
df['text'] = df['text'].apply(remove_punc)

In [ ]:
def remove_numbers(txt):
  new = ""
  for i in txt:
    if not i.isdigit():
      new += i
  return new

df['text'] = df['text'].apply(remove_numbers)

In [ ]:
def remove_emojis(txt):
  new = ""
  for i in txt:
    if i.isascii():
      new += i
  return new

df['text'] = df['text'].apply(remove_emojis)

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [ ]:
nltk.download('stopwords')
nltk.download('punkt')
nltk.download("punkt_tab")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [ ]:
def remove(txt):
  words = word_tokenize(txt)
  new = [word for word in words if word not in stop_words]
  return ' '.join(new)

df['text'] = df['text'].apply(remove)

In [ ]:
df.loc[1]['text']

'wulvob get medircations online qnb ikud viagra escapenumber escapenumber levitra escapenumber escapenumber cialis escapenumber escapenumber imitrex escapenumber escapenumber flonax escapenumber escapenumber ultram escapenumber escapenumber vioxx escapenumber escapenumber ambien escapenumber escapenumber valium escapenumber escapenumber xannax escapenumber escapenumber soma escapenumber meridia escapenumber escapenumber escapenumber escapenumber cysfrt ever stopped wonder much average man pays mediecines ap painkillers drugs improve quality life weight reducing tablets many escapenumber whats worse mediucine costs lot branded rfwur intrested http dmvrwm remunerativ net dfuaeirxygiq visit website escapenumber'

In [ ]:
df.head()

label                                               text
0      1  ounce feather bowl hummingbird opec moment ala...
1      1  wulvob get medircations online qnb ikud viagra...
2      0  computer connection cnn com wednesday escapenu...
3      1  university degree obtain prosperous future mon...
4      0  thanks answers guys know checked rsync manual ...

In [ ]:
df.shape

(7485, 2)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df['text'],df['label'],test_size = 0.20,random_state = 42)

In [ ]:
X_train

426                       vince ok send following interns
1593    get worth hershey chocolate ghirardelli chocol...
805     houston johnathon terry barbara mary fredrick ...
410     tat small move massive molecules clinical tria...
6259    agra best shop details fees pills cost escapen...
                              ...                        
5191    credit doesnt matter us family property want i...
5226    hello list im getting following errors try mai...
5390    hi somebody explain difference escapenumber sy...
860     alternative medicine database escapenumber mil...
7270    experienced sporadic difficulty maintaining er...
Name: text, Length: 5988, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer , CountVectorizer

In [ ]:
bow_vectorizer = CountVectorizer()
tfidf_vectorizer = TfidfVectorizer(ngram_range=(1,2), max_features=20000)

In [ ]:
X_train_idf = tfidf_vectorizer.fit_transform(X_train)
X_test_idf = tfidf_vectorizer.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [ ]:
lr_model = LogisticRegression()
lr_model.fit(X_train_idf, y_train)
lr_pred = lr_model.predict(X_test_idf)
print("\n--- Logistic Regression ---")
print(classification_report(y_test, lr_pred, digits=3))
print(accuracy_score(y_test,lr_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, lr_pred))


--- Logistic Regression ---
              precision    recall  f1-score   support

           0      0.987     0.938     0.961       705
           1      0.947     0.989     0.967       792

    accuracy                          0.965      1497
   macro avg      0.967     0.963     0.964      1497
weighted avg      0.966     0.965     0.965      1497

0.9645958583834335
Confusion Matrix:
 [[661  44]
 [  9 783]]


In [ ]:
from sklearn.svm import LinearSVC

In [ ]:
svm_model = LinearSVC()
svm_model.fit(X_train_idf, y_train)
svm_pred = svm_model.predict(X_test_idf)
print("\n--- Linear SVM ---")
print(classification_report(y_test, svm_pred, digits=3))
print(accuracy_score(y_test,svm_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, svm_pred))


--- Linear SVM ---
              precision    recall  f1-score   support

           0      0.987     0.966     0.976       705
           1      0.970     0.989     0.979       792

    accuracy                          0.978      1497
   macro avg      0.979     0.977     0.978      1497
weighted avg      0.978     0.978     0.978      1497

0.9779559118236473
Confusion Matrix:
 [[681  24]
 [  9 783]]


In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

mnb_model = MultinomialNB()

mnb_model.fit(X_train_idf, y_train)

mnb_pred = mnb_model.predict(X_test_idf)

print("-- Multinomial Naive Bayes ---")
print(classification_report(y_test, mnb_pred))
print("Accuracy:", accuracy_score(y_test, mnb_pred))

print("Confusion Matrix:\n", confusion_matrix(y_test, mnb_pred))

-- Multinomial Naive Bayes ---
              precision    recall  f1-score   support

           0       0.96      0.97      0.96       705
           1       0.97      0.97      0.97       792

    accuracy                           0.97      1497
   macro avg       0.97      0.97      0.97      1497
weighted avg       0.97      0.97      0.97      1497

Accuracy: 0.9659318637274549
Confusion Matrix:
 [[681  24]
 [ 27 765]]


In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
# -------------------------
# 1. Logistic Regression
# -------------------------

lr_model = LogisticRegression(max_iter=5000)

lr_params = {
    'C': [0.01, 0.1, 1, 10],
    'solver': ['liblinear', 'saga']
}

lr_grid = GridSearchCV(lr_model, lr_params, cv=5, scoring='accuracy', n_jobs=-1)
lr_grid.fit(X_train_idf, y_train)

lr_pred = lr_grid.predict(X_test_idf)
print("\n--- Logistic Regression ---")
print("Best Parameters:", lr_grid.best_params_)
print("CV Best Accuracy:", lr_grid.best_score_)
print("Test Accuracy:", accuracy_score(y_test, lr_pred))
print(classification_report(y_test, lr_pred, digits=3))
print("Confusion Matrix:\n", confusion_matrix(y_test, lr_pred))

# -------------------------
# 2. Linear SVM
# -------------------------
svm_model = LinearSVC(max_iter=5000)

svm_params = {
    'C': [0.01, 0.1, 1, 10],
    'loss': ['hinge', 'squared_hinge']
}

svm_grid = GridSearchCV(svm_model, svm_params, cv=5, scoring='accuracy', n_jobs=-1)
svm_grid.fit(X_train_idf, y_train)

svm_pred = svm_grid.predict(X_test_idf)
print("\n--- Linear SVM ---")
print("Best Parameters:", svm_grid.best_params_)
print("CV Best Accuracy:", svm_grid.best_score_)
print("Test Accuracy:", accuracy_score(y_test, svm_pred))
print(classification_report(y_test, svm_pred, digits=3))
print("Confusion Matrix:\n", confusion_matrix(y_test, svm_pred))

# -------------------------
# 3. Multinomial Naive Bayes
# -------------------------
mnb_model = MultinomialNB()

mnb_params = {
    'alpha': [0.01, 0.1, 0.5, 1.0],
    'fit_prior': [True, False]
}

mnb_grid = GridSearchCV(mnb_model, mnb_params, cv=5, scoring='accuracy', n_jobs=-1)
mnb_grid.fit(X_train_idf, y_train)

mnb_pred = mnb_grid.predict(X_test_idf)
print("\n--- Multinomial Naive Bayes ---")
print("Best Parameters:", mnb_grid.best_params_)
print("CV Best Accuracy:", mnb_grid.best_score_)
print("Test Accuracy:", accuracy_score(y_test, mnb_pred))
print(classification_report(y_test, mnb_pred, digits=3))
print("Confusion Matrix:\n", confusion_matrix(y_test, mnb_pred))


--- Logistic Regression ---
Best Parameters: {'C': 10, 'solver': 'saga'}
CV Best Accuracy: 0.9756175357704221
Test Accuracy: 0.9766199064796259
              precision    recall  f1-score   support

           0      0.986     0.965     0.975       705
           1      0.969     0.987     0.978       792

    accuracy                          0.977      1497
   macro avg      0.977     0.976     0.977      1497
weighted avg      0.977     0.977     0.977      1497

Confusion Matrix:
 [[680  25]
 [ 10 782]]

--- Linear SVM ---
Best Parameters: {'C': 1, 'loss': 'squared_hinge'}
CV Best Accuracy: 0.9779550434238071
Test Accuracy: 0.9779559118236473
              precision    recall  f1-score   support

           0      0.987     0.966     0.976       705
           1      0.970     0.989     0.979       792

    accuracy                          0.978      1497
   macro avg      0.979     0.977     0.978      1497
weighted avg      0.978     0.978     0.978      1497

Confusion Matrix:

In [ ]:
best_svm_model = svm_grid.best_estimator_

In [ ]:
y_pred = best_svm_model.predict(X_test_idf)  # or any new TF-IDF matrix

# Evaluate
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=3))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9779559118236473
              precision    recall  f1-score   support

           0      0.987     0.966     0.976       705
           1      0.970     0.989     0.979       792

    accuracy                          0.978      1497
   macro avg      0.979     0.977     0.978      1497
weighted avg      0.978     0.978     0.978      1497

Confusion Matrix:
 [[681  24]
 [  9 783]]


In [ ]:
import joblib

In [ ]:
joblib.dump(best_svm_model, 'svm_model.pkl')
joblib.dump(tfidf_vectorizer, 'tfidf_vectorizer.pkl')


['tfidf_vectorizer.pkl']